project_id = "playpickle"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
major_version = 17

[db.seed]
enabled = false

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["playpickle://auth/callback", "http://localhost:8081/auth/callback"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true

[functions.push-dispatch]
verify_jwt = false
