import React,{useRef,useState} from 'react';
import {Image} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import * as Crypto from 'expo-crypto';
import {Screen,Title,Body,Card,Badge,Row,Chip,Field,Section,DataState,Notice,Button} from '../components/ui';
import {useData} from '../hooks/useData';
import {query,rpc} from '../lib/api';
import {dateTime,clockTime,localDate,money} from '../lib/format';
import {colors} from '../theme';
export default function Club(){
 const {id}=useLocalSearchParams();const [date,setDate]=useState(''),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const request=useRef(null);
 const club=useData(async()=>{const rows=await query('clubs',{select:'*,courts(*),opening_hours(*)',filters:{id}});if(!rows.length)throw new Error('This club is unavailable.');return rows[0];},[id],['clubs','courts']);
 const chosenDate=date||localDate(club.data?.timezone||'UTC');
 const availability=useData(()=>rpc('court_availability',{p_club_id:id,p_date:chosenDate}),[id,chosenDate],['availability_changes']);
 async function reserve(){setBusy(true);setError('');try{request.current ||= Crypto.randomUUID();const result=await rpc('create_booking',{p_court_id:selected.court_id,p_starts_at:selected.starts_at,p_ends_at:selected.ends_at,p_request_id:request.current});const bookingId=typeof result==='string'?result:result.id;router.push('/booking/'+bookingId);setSelected(null);request.current=null;availability.reload();}catch(e){setError(e.message);availability.reload();}finally{setBusy(false);}}
 return <Screen refreshing={club.loading} onRefresh={()=>{club.reload();availability.reload();}}><DataState state={club}>{club.data&&<><Badge>{club.data.area}</Badge><Title>{club.data.name}</Title>{club.data.photo_url&&<Image source={{uri:club.data.photo_url}} style={{width:'100%',height:210,borderRadius:20}} resizeMode="cover"/>}<Body>{club.data.description||'Welcome to your local pickleball community.'}</Body><Card><Body>{club.data.address}</Body><Body style={{color:colors.muted}}>All times shown in {club.data.timezone}.</Body><Row>{club.data.facilities?.map(f=><Badge key={f}>{f}</Badge>)}</Row><Body>Payment is arranged directly with the club.</Body><Body>Cancel at least {club.data.cancellation_hours} hours before your reservation.</Body></Card>
 <Section title="Opening hours"><Card>{club.data.opening_hours?.length?club.data.opening_hours.sort((a,b)=>a.weekday-b.weekday).map(h=><Row key={h.weekday} style={{justifyContent:'space-between'}}><Body>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][h.weekday]}</Body><Body>{h.opens_at.slice(0,5)} – {h.closes_at.slice(0,5)}</Body></Row>):<Body>The club has not published opening hours yet.</Body>}</Card></Section>
 <Section title="Pick your time"><Row>{[0,1,2].map(n=>{const value=localDate(club.data.timezone,n);return <Chip key={n} label={n===0?'Today':n===1?'Tomorrow':value.slice(5)} selected={chosenDate===value} onPress={()=>{setDate(value);setSelected(null);request.current=null;}}/>;})}</Row><Field label="Booking date (YYYY-MM-DD)" value={chosenDate} onChangeText={v=>{setDate(v);setSelected(null);request.current=null;}} placeholder="YYYY-MM-DD"/><Body style={{color:colors.muted}}>{club.data.booking_duration_minutes}-minute sessions · {club.data.timezone}</Body>
 <DataState state={availability} emptyTitle="No sessions for this date" emptyMessage="Choose another day or check back when the club adds availability.">{club.data.courts?.filter(c=>c.active).map(c=><Card key={c.id}><Title style={{fontSize:22}}>{c.name}</Title><Body>{c.indoor?'Indoor':'Outdoor'} · {c.surface} · {money(c.price_per_hour,c.currency)}/hour</Body><Row>{availability.data?.filter(s=>s.court_id===c.id).map(s=><Button key={s.starts_at} title={clockTime(s.starts_at,club.data.timezone)} variant={selected?.court_id===c.id&&selected?.starts_at===s.starts_at?'primary':'secondary'} disabled={!s.available} style={{minWidth:90}} onPress={()=>{setSelected(s);setError('');request.current=null;}}/>)}</Row></Card>)}</DataState></Section>
 {selected&&<Card style={{borderColor:colors.forest,borderWidth:2}}><Badge>Your session</Badge><Title style={{fontSize:22}}>{selected.court_name}</Title><Body>{dateTime(selected.starts_at,club.data.timezone)} – {clockTime(selected.ends_at,club.data.timezone)}</Body><Title style={{fontSize:25}}>{money(selected.price_total,selected.currency)}</Title><Body style={{color:colors.muted}}>Pay the club directly. Your court is reserved only after confirmation.</Body><Notice message={error} tone="error"/><Button title="Confirm reservation" onPress={reserve} loading={busy}/></Card>}
 </>}</DataState></Screen>;
}
