import React,{useState} from 'react';
import {useLocalSearchParams} from 'expo-router';
import {Screen,Title,Body,Eyebrow,Card,Field,Badge,Row,Chip,DataState,Section,Button,Action,Notice,Empty} from '../components/ui';
import {useData} from '../hooks/useData';
import {useAuth} from '../providers/AuthProvider';
import {query,rpc} from '../lib/api';
import {dateTime} from '../lib/format';
import {colors} from '../theme';
function RegisterTeam({tournament,reload}){
 const {user}=useAuth();const [name,setName]=useState(''),[search,setSearch]=useState(''),[players,setPlayers]=useState([]),[partner,setPartner]=useState(null),[message,setMessage]=useState('');
 return <Card><Title style={{fontSize:24}}>Bring your doubles partner.</Title><Body>Both players need a PlayPICKLE account and completed profile. Your partner must accept before the deadline.</Body><Field label="Team name" value={name} onChangeText={setName} maxLength={80}/><Field label="Find your partner by display name" value={search} onChangeText={setSearch} placeholder="At least 2 characters"/>
 <Action title="Find players" variant="secondary" run={async()=>{if(search.trim().length<2)throw new Error('Enter at least 2 characters.');return rpc('search_players',{p_search:search.trim()});}} onDone={rows=>{const results=rows.filter(p=>p.id!==user.id);setPlayers(results);setMessage(results.length?'':'No matching players. Ask your partner to complete their profile.');}}/>
 <Notice message={message}/>{players.map(p=><Button key={p.id} title={p.display_name+' · '+p.competition_category} variant={partner?.id===p.id?'primary':'secondary'} onPress={()=>setPartner(p)}/>)}{partner&&<Notice message={'Partner: '+partner.display_name}/>}
 <Action title="Register team & invite partner" disabled={!partner||!name.trim()} run={()=>rpc('register_team',{p_tournament_id:tournament.id,p_partner_id:partner.id,p_name:name.trim()})} onDone={reload}/>
 </Card>;
}
function Match({match,teams,timezone,isParticipant,reload}){
 const [report,setReport]=useState(false),[reason,setReason]=useState(''),[message,setMessage]=useState('');
 const team=id=>teams.find(t=>t.id===id)?.name||'Awaiting opponent';
 return <Card style={{borderLeftWidth:4,borderLeftColor:match.status==='verified'||match.status==='bye'?colors.forest:colors.border}}><Row><Badge>Match {match.position}</Badge><Badge>{match.status}</Badge></Row><Body style={{fontWeight:match.winner_team_id===match.team_a_id?'800':'500'}}>{team(match.team_a_id)}{match.score_a!==null?' · '+match.score_a:''}</Body><Body style={{fontWeight:match.winner_team_id===match.team_b_id?'800':'500'}}>{match.status==='bye'?'Bye':team(match.team_b_id)}{match.score_b!==null?' · '+match.score_b:''}</Body><Body style={{fontSize:14,color:colors.muted}}>{dateTime(match.starts_at,timezone)}{match.courts?.name?' · '+match.courts.name:''}</Body>
 {isParticipant&&match.status==='verified'&&!report&&<Button title="Report an incorrect result" variant="ghost" onPress={()=>setReport(true)}/>}
 {report&&<><Field label="What needs correcting?" value={reason} onChangeText={setReason} multiline/><Action title="Submit result report" run={async()=>{if(reason.trim().length<10)throw new Error('Please describe the issue in at least 10 characters.');return rpc('report_result',{p_match_id:match.id,p_reason:reason.trim()});}} onDone={()=>{setReport(false);setMessage('Report recorded. Administrators will review it; disputed tournament points are held.');reload();}}/><Button title="Close report" variant="ghost" onPress={()=>setReport(false)}/></>}<Notice message={message} tone="success"/>
 </Card>;
}
export default function Tournament(){
 const {id}=useLocalSearchParams(),{user}=useAuth();const [tab,setTab]=useState('Overview'),[withdraw,setWithdraw]=useState(false),[reason,setReason]=useState('');
 const state=useData(async()=>{const [events,teams,matches]=await Promise.all([query('tournaments',{select:'*,clubs(name,timezone,area,address)',filters:{id}}),query('teams',{filters:{tournament_id:id},order:'created_at'}),query('matches',{select:'*,courts(name)',filters:{tournament_id:id},order:'round'})]);if(!events[0])throw new Error('Tournament unavailable or unpublished.');return {tournament:events[0],teams,matches};},[id],['tournaments','teams','matches']);
 const t=state.data?.tournament,teams=state.data?.teams||[],matches=state.data?.matches||[],myTeam=teams.find(t=>t.status!=='withdrawn'&&(t.captain_id===user.id||t.partner_id===user.id)),canRegister=t?.status==='published'&&new Date(t.registration_deadline)>new Date();
 const rounds=[...new Set(matches.map(m=>m.round))].sort((a,b)=>a-b);
 return <Screen onRefresh={state.reload} refreshing={state.loading}><DataState state={state}>{t&&<><Row><Badge>{t.category} doubles</Badge><Badge>{t.status}</Badge></Row><Title>{t.title}</Title><Body>{t.clubs?.name} · {t.clubs?.area}</Body><Row>{['Overview','Teams','Bracket'].map(x=><Chip key={x} label={x} selected={tab===x} onPress={()=>setTab(x)}/>)}</Row>
 {tab==='Overview'&&<><Card><Eyebrow>GAME DAY</Eyebrow><Title style={{fontSize:24}}>{dateTime(t.starts_at,t.clubs?.timezone)}</Title><Body>{t.clubs?.address}</Body><Body>Club time zone: {t.clubs?.timezone}</Body><Body>{t.description}</Body><Body>Single-elimination doubles · {teams.filter(x=>x.status==='accepted').length}/{t.max_teams} accepted teams</Body><Body>Registration closes {dateTime(t.registration_deadline,t.clubs?.timezone)}.</Body></Card>
 {t.policy_snapshot&&<Card><Title style={{fontSize:22}}>Competition policy</Title><Body>Scoring and placement rules are saved with this event. Points count toward this club’s season and category.</Body><Body>One game to {t.policy_snapshot.game_points}, win by {t.policy_snapshot.win_by}.</Body><Body>Champion: {t.policy_snapshot.champion_points} points · Runner-up: {t.policy_snapshot.runner_up_points} · Semifinalists: {t.policy_snapshot.semifinal_points} · Other entrants: {t.policy_snapshot.participation_points}.</Body><Body>Report incorrect results within {t.policy_snapshot.dispute_hours} hours. Administrators resolve disputes before points are awarded.</Body><Body style={{color:colors.muted}}>PlayPICKLE competition points are not a certified skill rating.</Body></Card>}
 {t.champion_team_id&&<Card style={{backgroundColor:colors.lime}}><Eyebrow>TOURNAMENT CHAMPIONS</Eyebrow><Title>{teams.find(x=>x.id===t.champion_team_id)?.name}</Title></Card>}
 {myTeam?<Card><Eyebrow>YOUR TEAM</Eyebrow><Title style={{fontSize:24}}>{myTeam.name}</Title><Badge>{myTeam.status}</Badge>{myTeam.status==='pending'&&myTeam.partner_id===user.id?<><Body>Accept to confirm your place as this team’s partner.</Body><Action title="Accept partner invitation" run={()=>rpc('respond_team_invitation',{p_team_id:myTeam.id,p_accept:true})} onDone={state.reload}/><Action title="Decline invitation" variant="secondary" run={()=>rpc('respond_team_invitation',{p_team_id:myTeam.id,p_accept:false})} onDone={state.reload}/></>:myTeam.status==='pending'?<Body>Waiting for your partner to accept. Pending invitations expire when registration closes.</Body>:<Body>You’re registered. Match schedules and verified results appear in the bracket.</Body>}
 {t.status==='published'&&!withdraw&&<Button title="Withdraw team" variant="ghost" onPress={()=>setWithdraw(true)}/>}
 {withdraw&&<><Field label="Withdrawal reason" value={reason} onChangeText={setReason}/><Action title="Confirm team withdrawal" variant="danger" run={async()=>{if(!reason.trim())throw new Error('Enter a reason.');return rpc('withdraw_team',{p_team_id:myTeam.id,p_reason:reason.trim()});}} onDone={()=>{setWithdraw(false);state.reload();}}/><Button title="Keep registration" variant="ghost" onPress={()=>setWithdraw(false)}/></>}</Card>:canRegister?<RegisterTeam tournament={t} reload={state.reload}/>:<Notice message="Registration is closed. You can follow the teams and bracket here."/>}</>}
 {tab==='Teams'&&(teams.length?teams.map(team=><Card key={team.id}><Row><Title style={{fontSize:22}}>{team.name}</Title><Badge>{team.status}</Badge></Row>{team.placement&&<Body>Final placement: {team.placement}</Body>}</Card>):<Empty title="The court is open" message="Accepted doubles teams will appear here."/>)}
 {tab==='Bracket'&&(matches.length?rounds.map(round=><Section key={round} title={round===Math.max(...rounds)?'Final':'Round '+round}>{matches.filter(m=>m.round===round).sort((a,b)=>a.position-b.position).map(m=><Match key={m.id} match={m} teams={teams} timezone={t.clubs?.timezone} isParticipant={!!myTeam&&[m.team_a_id,m.team_b_id].includes(myTeam.id)} reload={state.reload}/>)}</Section>):<Empty title="The bracket is coming" message="The club generates the bracket after registration closes. Accepted teams and byes will appear here."/>)}
 </>}</DataState></Screen>;
}
