import React, { useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNetInfo } from '@react-native-community/netinfo';
import { colors } from '../theme';
export function Screen({ children, refreshing, onRefresh, style, topSafe }) {
  const net = useNetInfo();
  return <SafeAreaView style={s.safe} edges={topSafe?['top','left','right','bottom']:['left','right','bottom']}><KeyboardAvoidingView style={s.safe} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={[s.screen, style]} refreshControl={onRefresh ? <RefreshControl refreshing={!!refreshing} onRefresh={onRefresh} tintColor={colors.forest}/> : undefined}>
    {net.isConnected === false && <Notice message="You're offline. Connect to refresh information or save changes." tone="error"/>}{children}
  </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
export function Body({ children, style, ...props }) { return <Text {...props} style={[s.body, style]}>{children}</Text>; }
export function Title({ children, style }) { return <Text accessibilityRole="header" style={[s.title, style]}>{children}</Text>; }
export function Eyebrow({ children, light }) { return <Text style={[s.eyebrow, light && {color: colors.lime}]}>{children}</Text>; }
export function Card({ children, style, onPress }) { return onPress ? <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[s.card,style,pressed&&{opacity:.8}]}>{children}</Pressable> : <View style={[s.card,style]}>{children}</View>; }
export function Row({ children, style }) { return <View style={[s.row,style]}>{children}</View>; }
export function Section({ title, children, action, onPress }) { return <View style={s.section}><Row style={{justifyContent:'space-between'}}><Text accessibilityRole="header" style={s.sectionTitle}>{title}</Text>{action && <Pressable accessibilityRole="button" onPress={onPress} style={s.link}><Body style={{fontWeight:'700',color:colors.forest}}>{action} →</Body></Pressable>}</Row>{children}</View>; }
export function Button({ title, onPress, variant='primary', loading, disabled, icon, style }) {
  const blocked = disabled || loading;
  return <Pressable accessibilityRole="button" accessibilityState={{disabled:!!blocked,busy:!!loading}} disabled={blocked} onPress={onPress} style={({pressed})=>[s.button,variant==='secondary'&&s.secondary,variant==='ghost'&&s.ghost,variant==='danger'&&{backgroundColor:colors.danger},variant==='lime'&&{backgroundColor:colors.lime},(blocked||pressed)&&{opacity:.5},style]}>
    {loading ? <ActivityIndicator color={variant==='primary'?colors.white:colors.forest}/> : <>{icon&&<Ionicons name={icon} size={20} color={variant==='primary'?colors.white:colors.forest}/>}<Text style={[s.buttonText,(variant==='secondary'||variant==='ghost'||variant==='lime')&&{color:colors.forest}]}>{title}</Text></>}
  </Pressable>;
}
export function Field({label,style,...props}) { return <View style={s.field}><Body style={s.label}>{label}</Body><TextInput accessibilityLabel={label} placeholderTextColor={colors.muted} autoCorrect={false} style={[s.input,props.multiline&&{minHeight:100,textAlignVertical:'top'},style]} {...props}/></View>; }
export function Badge({children,style}) { return <View style={[s.badge,style]}><Text style={s.badgeText}>{String(children).replaceAll('_',' ')}</Text></View>; }
export function Chip({label,selected,onPress}) { return <Pressable accessibilityRole="button" accessibilityState={{selected:!!selected}} onPress={onPress} style={[s.chip,selected&&{backgroundColor:colors.forest,borderColor:colors.forest}]}><Text style={{fontSize:15,fontWeight:'600',color:selected?colors.white:colors.ink}}>{label}</Text></Pressable>; }
export function Empty({title='Nothing here yet',message}) {return <Card style={{alignItems:'center',paddingVertical:28}}><Ionicons name="tennisball-outline" size={32} color={colors.forest}/><Title style={{fontSize:21,textAlign:'center'}}>{title}</Title>{message&&<Body style={{textAlign:'center',color:colors.muted}}>{message}</Body>}</Card>;}
export function Notice({message,tone='info'}) { if(!message)return null;return <View accessibilityRole="alert" style={[s.notice,tone==='error'&&{backgroundColor:'#FBECE9'},tone==='success'&&{backgroundColor:'#E6F2DC'}]}><Body style={{color:tone==='error'?colors.danger:colors.forest}}>{message}</Body></View>; }
export function Loading(){ return <View style={{padding:40}}><ActivityIndicator size="large" color={colors.forest}/><Body style={{textAlign:'center',marginTop:12}}>Getting things ready…</Body></View>; }
export function DataState({state,children,emptyTitle,emptyMessage}) { if(state.loading&&!state.data)return <Loading/>;if(state.error)return <View style={{gap:10}}><Notice message={state.error} tone="error"/><Button title="Try again" variant="secondary" onPress={state.reload}/></View>;if(Array.isArray(state.data)&&!state.data.length)return <Empty title={emptyTitle} message={emptyMessage}/>;return children; }
export function Action({title,run,onDone,variant='primary',disabled}) {const [busy,setBusy]=useState(false),[error,setError]=useState('');return <View style={{gap:8}}><Button title={title} variant={variant} disabled={disabled} loading={busy} onPress={async()=>{setBusy(true);setError('');try{const result=await run();await onDone?.(result);}catch(e){setError(e.message||'Unable to save. Please try again.');}finally{setBusy(false);}}}/><Notice tone="error" message={error}/></View>;}
export function Brand(){return <Image source={require('../../assets/playpickle-logo.png')} accessibilityLabel="PlayPICKLE" resizeMode="contain" style={{width:158,height:51}}/>;}
export function CourtArt(){return <View accessible={false} style={s.art}><View style={s.court}><View style={s.courtMid}/><View style={s.courtKitchen}/><View style={s.courtLine}/></View><View style={s.ball}><View style={s.dot}/><View style={s.dot}/><View style={s.dot}/></View></View>;}
const s=StyleSheet.create({
safe:{flex:1,backgroundColor:colors.paper},screen:{padding:20,paddingBottom:40,gap:20,width:'100%',maxWidth:800,alignSelf:'center',flexGrow:1},
body:{fontSize:16,lineHeight:24,color:colors.ink},title:{fontSize:30,lineHeight:36,fontWeight:'800',letterSpacing:-.7,color:colors.ink},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:colors.forest},
card:{padding:20,borderRadius:20,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,gap:12},row:{flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:10},section:{gap:14},sectionTitle:{fontSize:22,fontWeight:'700',color:colors.ink,flexShrink:1},link:{minHeight:44,justifyContent:'center'},
button:{minHeight:52,paddingVertical:14,paddingHorizontal:20,borderRadius:14,backgroundColor:colors.forest,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:10},secondary:{backgroundColor:colors.soft,borderWidth:1,borderColor:colors.border},ghost:{backgroundColor:'transparent'},buttonText:{fontSize:16,fontWeight:'700',color:colors.white,textAlign:'center'},
field:{gap:7},label:{fontSize:14,fontWeight:'700'},input:{borderWidth:1,borderColor:colors.border,borderRadius:12,paddingHorizontal:15,paddingVertical:14,minHeight:52,fontSize:16,color:colors.ink,backgroundColor:colors.white},
badge:{alignSelf:'flex-start',borderRadius:8,paddingHorizontal:10,paddingVertical:5,backgroundColor:colors.soft},badgeText:{fontSize:12,fontWeight:'700',color:colors.forest,textTransform:'uppercase',letterSpacing:.5},chip:{borderWidth:1,borderColor:colors.border,borderRadius:24,paddingHorizontal:17,paddingVertical:12,minHeight:44,justifyContent:'center',backgroundColor:colors.white},
notice:{borderRadius:12,padding:16,backgroundColor:colors.soft},art:{height:148,position:'relative',overflow:'hidden',marginVertical:8},court:{width:'84%',height:124,borderWidth:2,borderColor:'#759A85',alignSelf:'center',transform:[{rotate:'-8deg'}],marginTop:12},courtMid:{position:'absolute',left:'50%',height:'100%',borderLeftWidth:2,borderColor:'#759A85'},courtKitchen:{position:'absolute',top:'32%',height:'36%',width:'100%',borderTopWidth:2,borderBottomWidth:2,borderColor:'#759A85'},courtLine:{position:'absolute',top:'50%',width:'100%',borderTopWidth:2,borderColor:colors.white},ball:{position:'absolute',right:'10%',top:36,width:62,height:62,borderRadius:31,backgroundColor:colors.lime,flexDirection:'row',gap:6,alignItems:'center',justifyContent:'center',transform:[{rotate:'-25deg'}]},dot:{width:9,height:9,borderRadius:5,backgroundColor:colors.forest}
});
